### PR TITLE
More intuitive catalyst display

### PR DESCRIPTION
**Pull request by knoxx093**
Displays catalysts required as a count that decreases until requirement is met.

Old function was to stop displaying catalyst as soon as 1 item was provided.

Suggest re-working algorithm to require catalysts in correct spot.
This change doesn't work if catalysts are in weird spots and the helper images don't really make sense that way either.

### CODE REVIEW

**Comment by knoxx093** [comment]
I missed a thing on this pull. Just leave it for now.

**Comment by einsteinsci** [comment]
Should I close it so you can submit another PR or should I wait for the next few commits?

**Comment by knoxx093** [comment]
Go ahead and close it. I'll submit again when I fix the issue. Thanks.

**Comment by einsteinsci** [comment]
Buy #106 in that commit I meant #107.

**Pull request closed without merging**
