### PR TITLE
fix #114 ?

### LINKED ISSUE #114: Yet another crash
Hello fellows, i guess nei unnecessary for playing with mod, because when im look through the food cook recipes it give me a crash, am i doing wrong?
Im even disable all of modules, that dont work :(
http://pastebin.com/eL9x0nLi

### PR DESCRIPTION
**Pull request by knoxx093**
Fixes # 114?

### CODE REVIEW

**Comment by knoxx093** [comment]
In eclipse I end up with a warning about List<Object> not being good enough, thus the second change.

**Comment by einsteinsci** [comment]
I think I have the main issue fixed, but I found that right-clicking on fuels to find their usages causes a divide by zero crash. The problem is, none of my code shows up in the stacktrace.

**Comment by knoxx093** [comment]
A little investigation leads me to think that may be an NEI bug of some sort. best I can tell its because  a list that should never be empty is returning size 0

**Comment by knoxx093** [comment]
closing request as branch is going to go out of sync now.

**Pull request closed without merging**
