### PR TITLE
Fix to the wrong catalyst removed and related item ghost issues.

### PR DESCRIPTION
**Pull request by knoxx093**
Appears to fix issues discussed in #100

### CODE REVIEW

**Comment by knoxx093** [comment]
I'm only able to reproduce this behavior by putting in additional mats 1 at a time. If i drop a stack in it works fine. Perhaps this is a separate bug.

**Comment by einsteinsci** [comment]
Apparently `InventoryWorkbenchAdditionalMaterials.setInventorySlotContents()` isn't getting called when one or more of the item already is in the slot. Thus, `eventHandler.onCraftMatrixChanged(this);` isn't getting called, causing this latest bug.

**Comment by knoxx093** [comment]
I'm assuming this is a residual effect of vanilla table not caring how many of a thing are in any given slot. I can spend some more time looking into this later today.

**Comment by einsteinsci** [comment]
Putting `eventHandler.onCraftMatrixChanged(this);` inside of `InventoryWorkbenchAdditionalMaterials.markDirty()` (line 122) seems to fix it. I'll merge the PR and add that last line in myself.

**Pull request merged**
